### ISSUE TITLE
set_input_names confusion

### ISSUE THREAD

**Issue by bminixhofer** [snipsco/tract#296]
I've got CI working now for tractjs. I am using a squeezenet model where I have working .pb and .onnx files. I've added tests for the default (no options) and input facts (and already fixed a bug ;) ).

But I can't quite get custom inputs to work. I'd like to set the inputs of the ONNX model ([link](https://github.com/bminixhofer/tractjs/blob/master/demos/public/squeezenet/squeezenet1_1.onnx)) to the nodes `squeezenet0_conv8_fwd` and `squeezenet0_conv9_fwd`. But I get a strange error:

`Cargo.toml`
```toml
[package]
name = "tractinputtest"
version = "0.1.0"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tract-onnx = { git = "https://github.com/snipsco/tract/" }
```

`src/main.rs`
```rust
use tract_onnx::prelude::*;

fn main() -> TractResult<()> {
    let _model = tract_onnx::onnx()
        .model_for_path("squeezenet1_1.onnx")?
        .with_input_names(&["squeezenet0_conv8_fwd", "squeezenet0_conv9_fwd"])?
        .into_optimized();

    Ok(())
}
```

```
➜  ~/Documents/Experiments/tractinputtest git:(master) ✗ cargo run
   Compiling tractinputtest v0.1.0 (/Users/bminixhofer/Documents/Experiments/tractinputtest)
    Finished dev [unoptimized + debuginfo] target(s) in 4.37s
     Running `target/debug/tractinputtest`
thread 'main' panicked at 'no entry found for key', /Users/bminixhofer/.cargo/git/checkouts/tract-9a24dc151f0802d9/cfd5b19/core/src/model/compact.rs:68:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

But I see the nodes when running:
`tract squeezenet1_1.onnx -i 1x3x224x224xF32 --pass analyse`

I am also not sure about the difference between `set_input_names`and `set_input_outlets` / which I should use. Could you elaborate?
